# Numpy

## How to import

In [2]:
import numpy as np

## create new numpy object

In [2]:
a = np.arange(24)

## get numpy object shape

In [4]:
a.shape

(24,)

## change the numpy shape

In [10]:
a.shape = (4, 6)

In [11]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## reshape numpy array

In [12]:
a = np.arange(24)
a.reshape(8, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

## zeros, ones

In [3]:
b=np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## create numpy object from list

In [6]:
b = np.asarray([[1,2,3], [2,3,4], [4,5,6]])
b

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

## numpy slice, same as list slice

In [7]:
b[1:]

array([[2, 3, 4],
       [4, 5, 6]])

In [8]:
b[:1]

array([[1, 2, 3]])

## numpy broadcast

In [9]:
c = np.arange(3)

In [10]:
b + c 

array([[1, 3, 5],
       [2, 4, 6],
       [4, 6, 8]])